### ISSUE TITLE
RSA computation algorithm not in line with creator paper.

### ISSUE THREAD

**Issue by Fheilmann** [bobvanluijt/Bitcoin-explained#1]
I have found a discrepancy between the RSA paper by Ron Rivest, Adi Shamir, and Leonard Adleman and the corresponding wikipedia article which also includes your code listing:

The **paper** instructs to **choose d as co-prime to phi(n)** and **compute e as modular multiplicative inverse of d (modulo φ(n)).**

The old version of **wikipedia** as well as your code listing **choose e as co-prime to phi(n)** and **compute d as modular multiplicative inverse of d (modulo φ(n)).**

I fixed the code listing in the wikipedia entry. To bring your version in line (which it should be since it is cited as source) the following two lines need to be changed:

`e = random_prime(1, t),`
`d = modular_multiplicative_inverse(e, t);`

needs to become 

`d = random_prime(1, t),`
`e = modular_multiplicative_inverse(d, t);`

Best Regards,

F.Heilmann

**Comment by bobvanluijt** [comment]
Awesome, thank you!

**Comment by Fheilmann** [comment]
Please revert these changes. Apparently the way RSA is standardized today is not in line with the paper. and thus your previous version was right after all. sorry for the confusion.

**Comment by bobvanluijt** [comment]
Aha, thanks. You have a source for this?

Revert is done: https://github.com/bobvanluijt/Bitcoin-explained/commit/66458f0c0134ca1d7fd8dca3154af42b8bd51156
